after_success:
  - |
    if [ -n "$TRAVIS_TAG" ]; then
        mkdir ~/.pgp
        echo $PGP_PUBLIC | base64 --decode > ~/.pgp/pubring
        echo $PGP_SECRET | base64 --decode > ~/.pgp/secring
        sbt ++$TRAVIS_SCALA_VERSION publishSigned native:publishSigned sonatypeRelease
    elif [ "$TRAVIS_BRANCH" == master ]; then
        mkdir ~/.pgp
        echo $PGP_PUBLIC | base64 --decode > ~/.pgp/pubring
        echo $PGP_SECRET | base64 --decode > ~/.pgp/secring
        sbt ++$TRAVIS_SCALA_VERSION publishSigned native:publishSigned
    fi
before_install:
  - sudo apt-get update -qq
deploy:
  api_key: $GITHUB_AUTH
  file: target/**.jar
  file_glob: true
  on:
    repo: lucidsoftware/lucid-aspell
    tags: true
  provider: releases
install:
  - sudo apt-get install gcc libaspell-dev libaspell15 aspell
jdk:
  - openjdk6
language: scala
scala:
  - 2.10.5
  - 2.11.6
script:
  - sbt ++$TRAVIS_SCALA_VERSION package native:package
